version: '2'

volumes:
  redis_data:
  rabbitmq_data:
  gateway_data:

services:
  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - '${FRONTEND_PORT_HOST}:${FRONTEND_PORT_CONTAINER}'
    environment:
      - VITE_MQTT_BROKER_HOST=${VITE_MQTT_BROKER_HOST}
      - VITE_MQTT_BROKER_PORT_WS=${VITE_MQTT_BROKER_PORT_WS}
      - VITE_MQTT_BROKER_USERNAME=${VITE_MQTT_BROKER_USERNAME}
      - VITE_MQTT_BROKER_PASSWORD=${VITE_MQTT_BROKER_PASSWORD}
      - VITE_MQTT_ENVIRONMENT_TOPICS=${VITE_MQTT_ENVIRONMENT_TOPICS}
      - VITE_MQTT_SENSOR_TOPICS=${VITE_MQTT_SENSOR_TOPICS}
      - VITE_MQTT_PLANNER_TOPCS=${VITE_MQTT_PLANNER_TOPCS}
      - VITE_DEFAULT_TEMPERATURE_MIN=${VITE_DEFAULT_TEMPERATURE_MIN}
      - VITE_DEFAULT_TEMPERATURE_MAX=${VITE_DEFAULT_TEMPERATURE_MAX}
      - VITE_DEFAULT_HUMIDITY_MIN=${VITE_DEFAULT_HUMIDITY_MIN}
      - VITE_DEFAULT_HUMIDITY_MAX=${VITE_DEFAULT_HUMIDITY_MAX}
      - VITE_DEFAULT_MOTION_LIGHT_DURATION=${VITE_DEFAULT_MOTION_LIGHT_DURATION}
      - VITE_DEFAULT_PRESSURE_THRESHOLD=${VITE_DEFAULT_PRESSURE_THRESHOLD}

  rabbitmq:
    build: ./messaging
    restart: always
    ports:
      - '${MQTT_BROKER_PORT_TCP}:${MQTT_BROKER_PORT_TCP}' # MQTT TCP port
      - '${MQTT_BROKER_PORT_WS}:${MQTT_BROKER_PORT_WS}' # MQTT WebSocket port
      # - '5672:5672' # AMQP port (not needed?)
      - '15672:15672' # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    expose:
      - ${MQTT_BROKER_PORT_TCP}
      - ${MQTT_BROKER_PORT_WS}
      # - 5672
      # - 15672

  redis:
    build: database/
    image: redis:7
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - ${REDIS_PORT}

  backend:
    build: ./backend
    restart: always
    # depends_on:
    #   - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    expose:
      - ${BACKEND_PORT}

  context:
    build: ./context
    restart: always
    environment:
      - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
      - MQTT_BROKER_PORT_TCP=${MQTT_BROKER_PORT_TCP}
      - MQTT_BROKER_USERNAME=${MQTT_BROKER_USERNAME}
      - MQTT_BROKER_PASSWORD=${MQTT_BROKER_PASSWORD}
      - MQTT_ENVIRONMENT_TOPICS=${MQTT_ENVIRONMENT_TOPICS}
      - MQTT_SENSOR_TOPICS=${MQTT_SENSOR_TOPICS}
      - MQTT_ACTUATOR_STATE_TOPICS=${MQTT_ACTUATOR_STATE_TOPICS}
      - MQTT_PLANNER_TOPCS=${MQTT_PLANNER_TOPCS}
      - DEFAULT_TEMPERATURE_MIN=${DEFAULT_TEMPERATURE_MIN}
      - DEFAULT_TEMPERATURE_MAX=${DEFAULT_TEMPERATURE_MAX}
      - DEFAULT_HUMIDITY_MIN=${DEFAULT_HUMIDITY_MIN}
      - DEFAULT_HUMIDITY_MAX=${DEFAULT_HUMIDITY_MAX}
      - DEFAULT_MOTION_LIGHT_DURATION=${DEFAULT_MOTION_LIGHT_DURATION}
      - DEFAULT_PRESSURE_THRESHOLD=${DEFAULT_PRESSURE_THRESHOLD}
    # depends_on:
    #   - rabbitmq

  simulated-devices:
    build: ./simulated-devices
    restart: always
    environment:
      - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
      - MQTT_BROKER_PORT_TCP=${MQTT_BROKER_PORT_TCP}
      - MQTT_BROKER_USERNAME=${MQTT_BROKER_USERNAME}
      - MQTT_BROKER_PASSWORD=${MQTT_BROKER_PASSWORD}
      - MQTT_ENVIRONMENT_TOPICS=${MQTT_ENVIRONMENT_TOPICS}
      - MQTT_SENSOR_TOPICS=${MQTT_SENSOR_TOPICS}
      - MQTT_ACTUATOR_COMMAND_TOPICS=${MQTT_ACTUATOR_COMMAND_TOPICS}
      - MQTT_ACTUATOR_STATE_TOPICS=${MQTT_ACTUATOR_STATE_TOPICS}
      - DEFAULT_TEMPERATURE_MIN=${DEFAULT_TEMPERATURE_MIN}
      - DEFAULT_TEMPERATURE_MAX=${DEFAULT_TEMPERATURE_MAX}
      - DEFAULT_TEMPERATURE_UPPER=${DEFAULT_TEMPERATURE_UPPER}
      - DEFAULT_TEMPERATURE_INTERVAL=${DEFAULT_TEMPERATURE_INTERVAL}
      - DEFAULT_TEMPERATURE_INCREASE_RATE=${DEFAULT_TEMPERATURE_INCREASE_RATE}
      - DEFAULT_TEMPERATURE_DECREASE_RATE=${DEFAULT_TEMPERATURE_DECREASE_RATE}
      - DEFAULT_HUMIDITY_MIN=${DEFAULT_HUMIDITY_MIN}
      - DEFAULT_HUMIDITY_MAX=${DEFAULT_HUMIDITY_MAX}
      - DEFAULT_HUMIDITY_UPPER=${DEFAULT_HUMIDITY_UPPER}
      - DEFAULT_HUMIDITY_INTERVAL=${DEFAULT_HUMIDITY_INTERVAL}
      - DEFAULT_HUMIDITY_INCREASE_RATE=${DEFAULT_HUMIDITY_INCREASE_RATE}
      - DEFAULT_HUMIDITY_DECREASE_RATE=${DEFAULT_HUMIDITY_DECREASE_RATE}

  planner:
    build: ./planner
    restart: always
    # depends_on:
    #   - rabbitmq

  fast-downward:
    build: ./planner
    image: fast-downward
    volumes:
      - ./problems:/problems # directory for PDDL files
    working_dir: /fast-downward
    entrypoint: ['./fast-downward.py']

  gateway:
    image: kpine/zwave-js-server:latest
    restart: always
    privileged: true
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
    environment:
      USB_PATH: ${GATEWAY_USB_PATH}
      S0_LEGACY_KEY: ${GATEWAY_S0_LEGACY_KEY}
    volumes:
      - gateway_data:/cache
