version: '2'

volumes:
  redis_data:
  rabbitmq_data:
  gateway_data:
  pddl_data:
  postgres_data:

services:
  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - '80:3000'
    environment:
      - VITE_MQTT_BROKER_HOST=rabbitmq
      - VITE_MQTT_BROKER_PORT_WS=15675
      - VITE_MQTT_BROKER_USERNAME=guest
      - VITE_MQTT_BROKER_PASSWORD=guest
      - VITE_MQTT_ENVIRONMENT_TOPICS=env/+
      - VITE_MQTT_SENSOR_TOPICS=sensor/+
      - VITE_MQTT_PLANNER_TOPICS=planner/+
      - VITE_DEFAULT_TEMPERATURE_MIN=18
      - VITE_DEFAULT_TEMPERATURE_MAX=20
      - VITE_DEFAULT_HUMIDITY_MIN=40
      - VITE_DEFAULT_HUMIDITY_MAX=50
      - VITE_DEFAULT_MOTION_LIGHT_DURATION=30
      - VITE_DEFAULT_PRESSURE_THRESHOLD=100

  rabbitmq:
    build: ./messaging
    restart: always
    ports:
      - '1883:1883' # MQTT TCP port
      - '15675:15675' # MQTT WebSocket port
      - '15672:15672' # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    expose:
      - 1883
      - 15675
      # - 5672
      # - 15672

  redis:
    build: database/
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379

  postgres:
    build: ./postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build: ./backend
    restart: always
    # depends_on:
    #   - postgres
    #   - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - '8000:8000'

  context:
    build: ./context
    restart: always
    # depends_on:
    #   - rabbitmq
    environment:
      - MQTT_BROKER_HOST=rabbitmq
      - MQTT_BROKER_PORT_TCP=1883
      - MQTT_BROKER_USERNAME=guest
      - MQTT_BROKER_PASSWORD=guest
      - MQTT_ENVIRONMENT_TOPICS=env/+
      - MQTT_SENSOR_TOPICS=sensor/+
      - MQTT_ACTUATOR_STATE_TOPICS=actuator/+/state
      - MQTT_PLANNER_TOPCS=planner/+
      - DEFAULT_TEMPERATURE_MIN=18
      - DEFAULT_TEMPERATURE_MAX=20
      - DEFAULT_HUMIDITY_MIN=40
      - DEFAULT_HUMIDITY_MAX=50
      - DEFAULT_MOTION_LIGHT_DURATION=30
      - DEFAULT_PRESSURE_THRESHOLD=100

  simulated-devices:
    build: ./simulated-devices
    restart: always
    # depends_on:
    #   - rabbitmq
    environment:
      - MQTT_BROKER_HOST=rabbitmq
      - MQTT_BROKER_PORT_TCP=1883
      - MQTT_BROKER_USERNAME=guest
      - MQTT_BROKER_PASSWORD=guest
      - MQTT_ENVIRONMENT_TOPICS=env/+
      - MQTT_SENSOR_TOPICS=sensor/+
      - MQTT_ACTUATOR_COMMAND_TOPICS=actuator/+/command
      - MQTT_ACTUATOR_STATE_TOPICS=actuator/+/state
      - DEFAULT_TEMPERATURE_MIN=18
      - DEFAULT_TEMPERATURE_MAX=20
      - DEFAULT_TEMPERATURE_UPPER=5
      - DEFAULT_TEMPERATURE_INTERVAL=5
      - DEFAULT_TEMPERATURE_INCREASE_RATE=0.5
      - DEFAULT_TEMPERATURE_DECREASE_RATE=0.8
      - DEFAULT_HUMIDITY_MIN=40
      - DEFAULT_HUMIDITY_MAX=50
      - DEFAULT_HUMIDITY_UPPER=10
      - DEFAULT_HUMIDITY_INTERVAL=5
      - DEFAULT_HUMIDITY_INCREASE_RATE=3.0
      - DEFAULT_HUMIDITY_DECREASE_RATE=4.5

  fast-downward:
    build: ./planner
    image: fast-downward
    volumes:
      - pddl_data:/data # directory for PDDL files
    working_dir: /fast-downward
    entrypoint: ['./fast-downward.py']

  orchestration:
    build: ./orchestration
    restart: always
    volumes:
      - pddl_data:/data # directory for PDDL files
      # - /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.balena.features.balena-socket: '1'
    depends_on:
      - rabbitmq
    environment:
      - MQTT_BROKER_HOST=rabbitmq
      - MQTT_BROKER_PORT_TCP=1883
      - MQTT_BROKER_USERNAME=guest
      - MQTT_BROKER_PASSWORD=guest

  gateway:
    build: ./gateway
    restart: always
    privileged: true
    environment:
      - MQTT_SERVER=192.168.0.103
