version: '2'

volumes:
  redis_data:
  rabbitmq_data:

services:
  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - '80:3000'
  
  rabbitmq:
    image: rabbitmq:4-management
    restart: always
    ports:
      - "1883:1883"  # MQTT port
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-admin}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  redis:
    build: database/
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379

  backend:
    build: ./backend
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '4000:4000'
    expose:
      - 4000



