[project]
name = "context"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "paho-mqtt>=2.1.0",
    "python-dotenv>=1.1.1",
]
